### ISSUE TITLE
Is posible to get response headers?

### ISSUE THREAD

**Issue by chrisalexqm** [twg/devour#116]
Hello, actually I am working on a project that uses devour to consume endpoints. Now I need to get a response header(new_token_access in the image).
![2018-01-18_9-56-38](https://user-images.githubusercontent.com/28939131/35104142-f4725366-fc35-11e7-8f30-423bfc15b46f.png)

There is a way to get all response headers. Thanks a lot!

**Comment by danilobrinu** [comment]
```javascript
let responseMiddleware = {
  name: 'reponse-headers',
  res: (payload) => {
    return payload;
  }
}

jsonApi.insertMiddlewareAfter('response', responseMiddleware)
```

**Comment by chrisalexqm** [comment]
Done, thanks a lot! Closed :D

**Comment by danilobrinu** [comment]
@chrisalexqm you need close.
