### ISSUE TITLE
Relationship ids not included

### ISSUE THREAD

**Issue by danherd** [twg/devour#121]
With this definition:

```
jsonApi.define('user', {
  email: '',
  firstName: '',
  lastName: '',
  country: { jsonApi: 'hasOne' }
}
jsonApi.define('country')
```

If I send a create request, I get the following result:

```
{
  "data": {
    "type": "users",
    "id": "xxx",
    "attributes": {
      "email": "xxx@xxx.co.uk",
      "first-name": "xxx",
      "last-name": "xxx",
    },
    "relationships": {
      "country": {
        "data": {
          "type": "countries",
          "id": "GB"
        }
      }
    },
    "links": {
      "self": "https:\/\/api.test.dev\/users\/xxx"
    }
  },
  "meta": {
    "token-type": "Bearer",
    "access-token": "xxxxx",
    "expires-in": xxxxx,
    "refresh-token": "xxxxx",
    "message": "Logged in."
  }
}
```

But it is deserialised to this:

```
{
  data: {
    country: null,
    email": "xxx@xxx.co.uk",
    firstName: "xxx",
    id: "xxx",
    lastName:"xxx",
    links: {
      self: "https://api.test.dev/users/xxx"
    }
  },
  errors: undefined,
  links: undefined,
  meta: {
    "token-type": "Bearer",
    "access-token": "xxxxx",
    "expires-in": xxxxx,
    "refresh-token": "xxxxx",
    message: "Logged in."
  }
}
```

Why isn't the relationship ID included? I would expect something like the following:

```
{
  data: {
    country: { id: "GB" },
    email": "xxx@xxx.co.uk",
    firstName: "xxx",
    id: "xxx",
    lastName:"xxx",
    links: {
      self: "https://api.test.dev/users/xxx"
    }
  },
  errors: undefined,
  links: undefined,
  meta: {
    "token-type": "Bearer",
    "access-token": "xxxxx",
    "expires-in": xxxxx,
    "refresh-token": "xxxxx",
    message: "Logged in."
  }
}
```

**Comment by erikse** [comment]
Hey, have you tried adding `type` in your `hasOne` definition, e.g. 

 ```js
jsonApi.define('country')

jsonApi.define('user', {
  email: '',
  firstName: '',
  lastName: '',
  country: { 
    jsonApi: 'hasOne',
    type: 'country'
  }
})
```

Such as they are doing in the Devour tests:

https://github.com/twg/devour/blob/3836582fc823421ce32f318294b79ec6dec32ded/test/api/api-test.js#L749-L752

**Comment by danherd** [comment]
@erikse That didn't make a difference, unfortunately.

Closing this because I don't think it's currently possible to get any relationship data unless you manually include it. I've decided to start doing that anyway.

**Comment by erikse** [comment]
What does your create statement look like, do you pass the option `include: { 'country' }`

**Comment by danherd** [comment]
I changed my API so it automatically included the relationships I need (without having to pass `?include=xxx,yyy` in the query string.

**Comment by spawnia** [comment]
I just ran into the same issue.

There are cases where i just want to know the id of a relationship, without the overhead of actually including all of its data. On the server, `include` results in two tables being joined, which can actally be quite a large overhead when i just need the id anyways!

It would be super useful if the id can be put into the deserialized object, regardless of the resource being included or not - the information is there anyway so i think it should be available.
