### ISSUE TITLE
String interpolation in error message

### ISSUE THREAD

**Issue by aimeebooth** [twg/devour#124]
I've been seeing the following error message when trying to debug my application:

```devour error Error: API resource definition for model "${modelName}" not found.```

Should the [interpolation](https://github.com/twg/devour/blob/d58677126790d66886996b7716f94b8f75af9e43/src/index.js#L351) be changed to use backticks?

Example:
<img width="1267" alt="screen shot 2018-03-07 at 4 37 01 pm" src="https://user-images.githubusercontent.com/867658/37119657-136d5f70-2226-11e8-8261-a2032be45e9e.png">

**Comment by billxinli** [comment]
Yes.

**Comment by aimeebooth** [comment]
@billxinli I was considering creating a PR when I saw this was already open https://github.com/twg/devour/pull/106. Can it be merged?

**Comment by Emerson** [comment]
@aimeebooth thanks! I've just merged the PR that hopefully fixes this!
