### ISSUE TITLE
When patching a single field in a resource, all fields are listed as undefined

### ISSUE THREAD

**Issue by tomers** [twg/devour#141]
In the code:

When patching a single resource, for example I want to send a PATCH request to https://api.com/v1/items/123 with the following payload:
```json
{
  "data": {
    "id": "123",
    "type": "items",
    "attributes": {
      "field1": "value1"
    }
  }
}
```
Then I am actually sending a request with all other fields, i.e.
```json
{
  "data": {
    "id": "123",
    "type": "items",
    "attributes": {
      "field1": "value1",
      "field2": null,
      "field3": null,
      "field4": null,
      "field5": null
    }
  }
}
```

This is done due to the following code in `src/middleware/json-api/_serialize.js`:
```js
function resource (modelName, item) {
  // ...
  if (Boolean(attrValues) && attrValues.filter(val => val === undefined).length !== attrValues.length) {
    serializedResource.attributes = serializedAttributes
  }
  // ...
}
```
I think that non-specified fields should be removed.

**Comment by Auspicus** [comment]
This seems like a valuable patch to add. Do you wanna get a PR going? @tomers

**Comment by auvipy** [comment]
this might be need to be closed?

**Comment by tomers** [comment]
Thanks for the reminder!
