### ISSUE TITLE
Initializer should be an option

### ISSUE THREAD

**Issue by billxinli** [twg/devour#15]
Initializer should be an option.

Current: 
`new JsonApi('http://example.com', listOfMiddleware)`

The issue with this is that the minute we want to pass in additional option, maybe a header, or enable or disable logging, it becomes a headache to manage, and any other calls of the initializer will need to be changed. Where as with an option, we can easily add a key.

**Comment by derek-watson** [comment]
I agree and was going to make the same suggestion.
