### ISSUE TITLE
How to camelCase relationships

### ISSUE THREAD

**Issue by axsuul** [twg/devour#156]
Our relationships are being returned as dashed (kebab) style but devour doesn't appear to camelCase them as it typically does for attributes. Therefore, we're having to define our models like this:

```javascript
jsonApi.define('itinerary', {
  'conversation-group': {
    jsonApi: 'hasOne',
    type: 'conversation-groups',
  },
})
```

Any suggestions how we could define it like this instead?

```javascript
jsonApi.define('itinerary', {
  conversationGroup: {
    jsonApi: 'hasOne',
    type: 'conversation-groups',
  },
})
```

Thanks!

**Comment by luisgabrielroldan** [comment]
Hi guys! Great library!
I'm having the same issue, is there any plan to fix this?

**Comment by axsuul** [comment]
@luisgabrielroldan In the meantime, you can get around this by defining your own middleware to transform the keys

**Comment by rmcsharry** [comment]
@luisgabrielroldan, @axsuul  
I noticed there is a PR for this now: https://github.com/twg/devour/pull/174
It would be nice to get that merged :)
