### ISSUE TITLE
Support Bearer Tokens (e.g. JWT)

### ISSUE THREAD

**Issue by StephanMeijer** [twg/devour#157]
Support for authentication through for example jwt tokens:

`Authorization: Bearer ...........`

Will write this myself

**Comment by StephanMeijer** [comment]
that works, but why is Basic auth being handled as a first class citizen, but Bearer is not?

**Comment by billxinli** [comment]
The underlying library axios treats basic as first-class citizen. https://github.com/axios/axios

Should be easy enough to implement bearer token.

https://github.com/twg/devour/blob/master/src/middleware/json-api/req-http-basic-auth.js

**Comment by Auspicus** [comment]
It would be nice to have a utility method to allow for Bearer tokens.

**Comment by kevincoenegrachts** [comment]
I wrote an implementation for this: https://github.com/twg/devour/pull/200

**Comment by Auspicus** [comment]
This has been merged.
