### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by bernhardh** [twg/devour#169]
Maybe I am missunderstanding something, but this library is completely sync, right? Is there a way, to use it async with promise base? Something like:

```
jsonApi.find('post', 5).then(function(res){
   // Here is the response
});
```

I want to use it in a view app

**Comment by billxinli** [comment]
const res = await jsonApi.find('post', 5)

**Comment by mikevoets** [comment]
@billxinli It does not work here though:
```
SyntaxError: ... await is a reserved word (37:12)
  35 | });
  36 | 
> 37 | const res = await jsonApi.findAll('customers', { include: 'orders' })
```

**Comment by billxinli** [comment]
Is your function wrapped with async keyword?

**Comment by mikevoets** [comment]
@billxinli  No, it wasn't. Thanks.
