### ISSUE TITLE
clear cache changes not in latest version

### ISSUE THREAD

**Issue by I2olanD** [twg/devour#176]
Hello,

it appears, that the latest changes of clearing the cache, in the deserialization step, are not included in the latest npm release. Is it not published yet? Please confirm.

**Comment by vixone** [comment]
The changes regarding caching that are apparently merged in this commit: https://github.com/twg/devour/pull/154/commits 
are not present in the latest release, can you please investigate this?

**Comment by Auspicus** [comment]
I think this might have gone out with the latest patch.
