### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by Emerson** [twg/devour#183]
Howdy Everyone,

Happy to see this project is useful for so many people! I'm currently working full time over at [Closing Folders](https://www.closingfolders.com) and we don't use JSON-API spec, so my knowledge of this project is fading.

I still think there is big value in JSON-API and it seems like lots of folks are using this project so I'm interested to hear from anyone who might want to take a more active role in maintaining things. At this point I just drop in every few months, merge any obvious fixes, and release a patch version on NPM.

Anyways, please chime in if you're interested in helping out! You can also reach out directly at emerson.lackey@gmail.com. @tomers has also been helping to maintain things so it's worth chatting with him as well.

**Comment by Auspicus** [comment]
Hey @Emerson!

I'm working with a few others in the Drupal community on a Drupal specific adaptation of this library (see [Desarol/devour-drupal](https://github.com/Desarol/devour-drupal)). Thanks to how modular it is, we were able to get away with just defining models (and setting a custom collectionPath) so big 👍  for that.

I'd be happy to help out in maintaining the underlying devour client!

**Comment by Emerson** [comment]
@Auspicus - added you to this project. You should now have the ability to read/write/merge/manage issues.

I'll need to get you setup on npm as well so you can actually push releases

**Comment by Auspicus** [comment]
@Emerson Sure, how do we go about doing that? My npm username is `edisch`.

**Comment by Emerson** [comment]
@Auspicus - added to NPM as a maintainer. You should be able to push releases now. We have some stuff setup in the `package.json` file that handles releases. More often than not it's just `npm run release:patch`

**Comment by Auspicus** [comment]
Awesome. I'll take a look at everything today after work and see what we can get out.

**Comment by auvipy** [comment]
I use it with Django based REST JSON API projects. and have regular usage of it. I would love to help maintain this project.

**Comment by tijn** [comment]
In our company we're using devour in all our front-end projects. So logically we have an interest in fixing issues. I'll be glad to help out with maintenance.

**Comment by Emerson** [comment]
@tijn and @auvipy - Added you as admins to this repo, please feel free to keep it alive and well <3

**Comment by auvipy** [comment]
closing for now. will open if needed in future

**Comment by tomers** [comment]
Thanks @tijn and @auvipy for you contributions and your support for this project! Highly appreciated
