### ISSUE TITLE
Update or remove es6-promise dependency

### ISSUE THREAD

**Issue by justinhoward** [twg/devour#188]
Currently es6-promise is listed as a dependency and restricted to `^3.1.2` in `package.json`. That prevents updating to version 4.0.0 or higher. I see two solutions:

- Update the dependency to `>=3.1.2 <5.0.0` to allow the newest version
- Remove the dependency on `es6-promise` and rely on developers to choose their own polyfill if necessary.

The first is easiest and that might be a good quick fix. I'm guessing that the long-term solution is to remove the dependency and polyfill altogether. This would allow developers to choose their own polyfill or no polyfill at all.

**Comment by Auspicus** [comment]
I'm ok with us just updating the dependency for now. Do you want to get a PR up with that change? @justinhoward
