### ISSUE TITLE
Pre-compile with Babel for NPM users

### ISSUE THREAD

**Issue by grantjk** [twg/devour#20]
<img width="1190" alt="screenshot 2016-05-07 10 42 17" src="https://cloud.githubusercontent.com/assets/1066132/15092736/75d573e6-1440-11e6-9485-86dfcaa13cc7.png">

Warnings are being thrown when including devour through npm - causing our tests to fail. I don't know much more than that.. 🤓, but we've had to include it as a submodule for now to get around this.

**Comment by derek-watson** [comment]
The problem is that we're shipping ES6 code, when people use the package they should be importing sources precompiled with babel. 

I've re-titled this ticket to track that feature and will submit a PR covering it.

**Comment by derek-watson** [comment]
@grantjk if you update to the latest published version of the npm package it should work properly for you now.

**Comment by derek-watson** [comment]
Solved by #22

**Comment by grantjk** [comment]
Thanks @derek-watson !

**Comment by Emerson** [comment]
Thanks for this, was running into this on my project as well but wasn't sure how to fix it.
