### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by unicrus** [twg/devour#214]
Please consider adding type definitions.

**Comment by tijn** [comment]
could you create a pull request for that @unicrus ?

**Comment by taai** [comment]
@tijn Maybe rewrite everything to TypeScript instead? What do you think? I *think* I could help with that. :man_shrugging:

**Comment by tijn** [comment]
@taai i'm not willing to do the work but feel free to create a fork named devour.ts or so.

**Comment by Auspicus** [comment]
@auvipy or @taai I wouldn't mind putting some time in here to help with this. Has any work been done to start this off? How should we coordinate this?
