### ISSUE TITLE
Serialization of empty/null relationships in post, patch etc.

### ISSUE THREAD

**Issue by glsignal** [twg/devour#29]
First up: thanks for the work on this library; it's proving very useful :smile: :tada: 

I've noticed something that isn't quite to spec when attempting to create/update a resource, specifically how the serializer deals with relationships that either aren't present or are explicitly set to null.

Based on my interpretation of the spec for [creating resources](http://jsonapi.org/format/#crud-creating) and [updating relationships](http://jsonapi.org/format/#crud-updating-resource-relationships), an API expects relationships in a payload, null or otherwise, to contain a `data` key.

> If a relationship is provided in the relationships member of the resource object, its value MUST be a relationship object with a data member

### Problem

The current serializer, however, omits the `data` part, causing the payload to not be valid under version 1 of the spec.

As a quick example, I have two resources (comment, thread) declared as such:
```javascript
jsonApi.define('thread', {
  thread: {
    jsonApi: 'hasMany',
    type: 'comment'
  }
});

jsonApi.define('comment', {
  body: '',
  thread: {
    jsonApi: 'hasOne',
    type: 'thread'
  }
});
```

and I want to create a comment that isn't in any thread by doing the following:

```javascript
jsonApi.all('comment').post({ body: "An orphaned comment", thread: null });
```

I'd expect the following to be sent to the server
```json
{
  "data": {
    "type": "comments",
    "attributes": { "body": "An orphaned comment" },
    "relationships": {
      "thread": {
        "data": null
      }
    }
  }
}
```

However what is sent is slightly different (lack of `data` in the relationship)
```json
{
  "data": {
    "type": "comments",
    "attributes": { "body": "An orphaned comment" },
    "relationships": {
      "thread": null
    }
  }
}
```

And omitting the relationship entirely:

```javascript
jsonApi.all('comment').post({ body: "An ambiguous comment" });
```

Expected:
```json
{
  "data": {
    "type": "comments",
    "attributes": { "body": "An ambiguous comment" }
  }
}
```

results in the same invalid payload being sent.

### Solution

I'm having a think about some ways to change this behaviour in the serializer for the two cases here (deliberately setting it to null, and omitting it entirely). ~~This'll come in a PR at some point in the future, but for now do any thoughts or concerns come to mind if the serializer does get changed to produce the expected behaviour?~~
This is implemented in PR #30, any feedback or design queries are :+1: :ok_hand: :smile:

**Comment by Emerson** [comment]
I think this is resolved with your PR – feel free to reopen if I'm wrong
