### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by derek-watson** [twg/devour#3]
This library is awesome!

I wonder if it would hit the ear better if it were named simply `devour.js`. The name as it stands, while descriptive, is a little bit hard to say.

**Comment by Emerson** [comment]
if devour.js is available, I'm 100% in on it

**Comment by derek-watson** [comment]
Hmm, `devour` isn't available on npm, and adding `js` to it is a little bit redundant.

What if it was `devour-client` on npm, and simply twg/devour in github?

**Comment by Emerson** [comment]
^ let's do it 🎉

**Comment by Emerson** [comment]
Volia...

* https://www.npmjs.com/package/devour-client
* https://github.com/twg/devour

Also asked the designers about a logo, but that'll be a separate issue

**Comment by davidpellerin** [comment]
🔥
