### ISSUE TITLE
Support fetch

### ISSUE THREAD

**Issue by derek-watson** [twg/devour#4]
Would it be a good idea to use `fetch` under the hood instead of `axios`? 

> fetch is a better networking API being worked on by the standards committee and is already available in Chrome. It is available in React Native by default.

https://fetch.spec.whatwg.org/
https://facebook.github.io/react-native/docs/network.html

Here's a polyfill that can be used until native runtime support for fetch is widespread, which comes in at 11kb of unminified code instead of 32kb for axios, with the upside that the dependency disappears completely at some point in the future:

https://github.com/github/fetch

**Comment by stephenkubovic** [comment]
This would not work in Node would it?

**Comment by derek-watson** [comment]
Hmm, true. There's a `node-fetch` library for that environment instead.

https://github.com/bitinn/node-fetch
