### ISSUE TITLE
[Question] Trailing slashes support?

### ISSUE THREAD

**Issue by raizyr** [twg/devour#57]
I was going to create a PR to add a constructor option for building URLs with trailing slashes, but I wanted to check first if there was another solution I was missing.

**Comment by spiderbites** [comment]
Hi, no I don't believe there is, a PR would be appreciated!

**Comment by raizyr** [comment]
Ok, I can probably do that in the next couple days.

**Comment by raizyr** [comment]
Ok, before I get too far into this, I see #46 talking about adding to the url builder.  Might it be better to move the url builder parts to a new middleware type?

Currently the middleware runs:
```javascript
requestMiddleware.then(
    responseMiddleware
).catch(
    errorMiddleware
)
```

Moving it would change the call stack to something like:
```javascript
requestBuilderMiddleware.then(
    requestMiddleware
).then(
   responseMiddleware
).catch(
    errorMiddleware
)
```

The error middleware could  also be expanded to handle specific error types to better handle the differences between builder, request, or response errors.

Thoughts?
