### ISSUE TITLE
Create action with relationship

### ISSUE THREAD

**Issue by Maxoos** [twg/devour#60]
Hey, 

I am trying to send a create action with a relationship but the relationship does not include the data under it. This is what I did:

```
jsonApi.create('user/properties', {
    address: {
      street_number: '1',
      street_name: 'name',
    },
    headline: 'something'),
    description: 'description'),
    photos: [],
    floorplans: [],
  })
```  

What I get on the server side is this:

```
'data': {
   'type': "user/properties"
   'attributes': "the attributes - everything is fine here"
   'relationships': {
       'address': {
          'data': {
            'type': 'addresses'
         }
      }
   }
}
```

As you can see the data is missing under the address. Am I doing something wrong?

Thanks!

**Comment by spiderbites** [comment]
Hey, currently JSON API does not support creating embedded relationships.  See [here](https://github.com/cerebris/jsonapi-resources/issues/792#issuecomment-237942205) for a long discussion and some proposals.  [Here](https://github.com/json-api/json-api/issues/1089) is another very recent proposal that would allow this.

To create these objects you could use two requests:
```
jsonApi.create('address', {
  street_number: '1',
  street_name: 'name'
})
```
You should get a response back from the server with an `id`.  Then you can create the `user/properties` object with the address relationship by including this id.

```
jsonApi.create('user/properties', {
  address: { id: ID },
  headline: 'something',
  ...
})
```
