### ISSUE TITLE
How to handle api errors

### ISSUE THREAD

**Issue by dahliacreative** [twg/devour#66]
I'm trying to use your client, I'm using promises but have no idea how to handle errors back from the API, your documentation isn;t very clear, could someone point me in the right direction?

I'm currently implementing like this:
```
jsonApi.create('genre', genre).then((response) => {
 console.log(response)
})
```

If there is an error returned from the API then no response is consoled. I tried using catch but that doesn't return the response from the serve.

Any help would be greatly appreciated!

**Comment by Emerson** [comment]
Hmm, that's strange – I'm pretty certain that the `catch` callback should be getting passed the error.

One thing you should do is ensure that your API is responding with the correct error format outlined in the specification here: http://jsonapi.org/examples/#error-objects

Short of that, you could drop in your own custom error middleware and start debugging from that. You can find a basic example of that in the docs: https://github.com/twg/devour#your-first-middleware

**Comment by Maxoos** [comment]
There is definitely an issue, the error itself is not passed to catch.

**Comment by superp** [comment]
Try to use this:

```
const { response, error } = jsonApi.create(...).then(response => ({ response }))
.catch(error => ({ error }))
```

**Comment by Maxoos** [comment]
I have tried it, it would catch an error but not the actual error object with all the information. It would catch just a general error.

**Comment by ViktorChernyaev** [comment]
Whether you use middleware? Im handling errors by  error-middleware( { name: "custom-errors", error: (payload) => {/ * operations with payload * / return "something, that will given to your error in catch/error" } } ) and replacing default error middleware (jsonApi.replaceMiddleware ( "errors", errorMiddleware);)

**Comment by Emerson** [comment]
The latest release (2.0) has some new code that might help resolve this issue in a more graceful manner. Let us know 👍

**Comment by VinceBassman** [comment]
I was proceeding like ViktorChernyaev using the old version. Upgrading to 2.0 does not resolve the errors handling at all.
Payload returned by the function called:
`{

	"errors": [{
		"code": "unprocessable_entity",
		"detail": "Name has already been taken",
		"meta": {
			"attribute": "name",
			"message": "has already been taken"
		},
		"source": {
			"pointer": "/data/attributes/name"
		},
		"status": "422",
		"title": "Validation Error"
	}]
}`

Payload returned by the devour-client:
`
Error: Request failed with status code 422
    at createError (createError.js?16d0:16)
    at settle (settle.js?db52:18)
    at XMLHttpRequest.handleLoad (xhr.js?ec6c:77)
`

Is there something wrong in the errors payload returned by the API? Can you please help to get the full errors payload?

**Comment by Emerson** [comment]
Hmmm, I don't have time to look into this myself, but that is unfortunate. If anyone is feeling brave enough to sort this out and send in a PR I'm more than happy to get this merged and published.

**Comment by VinceBassman** [comment]
Ok, to make it work properly you just need to replace
`return buildErrors(payload.response.data);`
with
`return buildErrors(payload.response.data.errors);`
in your javascript file res-errors.js
