### ISSUE TITLE
Wrong Accept Header

### ISSUE THREAD

**Issue by IDragonfire** [twg/devour#70]
Your API have a wrong `Accept` Header

```
 payload.req.headers = {
	        'Content-Type': 'application/vnd.api+json',
	        'Accept': 'application/vnd.api+json'
	      }
```

`Accept` should be e.g. `application/json` otherwise it returns a `406 Not Acceptable`
see Specification: http://jsonapi.org/format/#content-negotiation-servers

![image](https://cloud.githubusercontent.com/assets/1217999/21639641/641aa802-d271-11e6-8406-ba5d7cceb870.png)

# Hotfix
`jsonApi.headers['Accept'] = 'application/json';`

**Comment by spiderbites** [comment]
I'm not following, the spec on my reading states that this is the right Accept header and looking at some other client implementations (e.g. https://github.com/emberjs/data/blob/a4b7b7095a07ba43f3e1aa8075d1d168ca9638d8/addon/adapters/json-api.js#L183) I see them doing the same thing.

**Comment by emmanueldaher** [comment]
The JSON API spec defines the correct Accept header as the following:

http://jsonapi.org/format/#content-negotiation-clients
> Clients MUST send all JSON API data in request documents with the header Content-Type: **application/vnd.api+json** without any media type parameters.

> Clients that include the JSON API media type in their Accept header MUST specify the media type there at least once without any media type parameters.

> Clients MUST ignore any parameters for the application/vnd.api+json media type received in the Content-Type header of response documents.

**Comment by IDragonfire** [comment]
my mistake, thank you very much for the fast replay
