### ISSUE TITLE
Nested includes

### ISSUE THREAD

**Issue by dahliacreative** [twg/devour#71]
So jsonApi let's you include nested relationships like /author?include=comments,comments.author

Questions can devour accommodate this, and if so how would I define my model? I'd expect something like:

```
{
  'comments': {
    'type': 'comments',
    'jsonApi': 'hasMany'.
    'author': {
      'type': 'users',
      'jsonApi': 'hasOne'
    }
  }
}
```

I've tried that but doesn't seem to work, if anyone could shed some light?

thanks

**Comment by dahliacreative** [comment]
Completely ignore me, I've figured it! Sorry, was having a brain fart.

**Comment by bmichelsen** [comment]
Please share the solution (no matter how trivial) in case someone else runs into the same problem.

**Comment by dahliacreative** [comment]
Ok cool so for nested relationships, say you are getting posts and want to include comments, and then want to include the comment author, your include query should look like:
`{ include: 'comments,comments.author' }`
Then where you define your models should be like:
```
jsonApi.define('post', {
  'title': '',
  'content': '',
  'comment': {
    'type': 'comments',
    'jsonApi': 'hasMany'
  }
})

jsonApi.define('comment', {
  'content': '',
  'author': {
    'type': 'users',
    'jsonApi': 'hasOne'
  }
})

jsonApi.define('author', {
 'name': ''
})
```

So basically I was trying to nest the author relationship inside the comments object inside where I was defining post instead of nesting it where I was defining comment.

It's simple when you think about it, I was just having a brain fart.
