### ISSUE TITLE
Parsing of Error Objects 

### ISSUE THREAD

**Issue by IDragonfire** [twg/devour#72]
Regardng the JSON API Spec (http://jsonapi.org/format/#errors)  this is a valid error response:

```json
{"errors":["ForbiddenAccessException"]}
```

It looks like devour require the optional parameter `pointer`
`TypeError: Cannot read property 'pointer' of undefined`
![image](https://cloud.githubusercontent.com/assets/1217999/22503761/85964fbe-e873-11e6-83d1-c3ec079a274a.png)

**Comment by bwvoss** [comment]
@IDragonfire devour expects every error object to follow the jsonapi spec: http://jsonapi.org/format/#error-objects

So you don't have a ``source`` property on your error, and the ``source`` must have a property of ``pointer`` that follows the ``/data/attributes`` format

**Comment by mateomurphy** [comment]
The default error middleware seems to be designed mostly to handle things like validation errors. It doesn't work properly for things like 404 errors or server errors, where having a `source` doesn't really make sense, and other parts of the error message that would be useful are discarded.

Fortunately it's trivial to replace it with a custom middleware, but perhaps it would make more sense to have a default middleware that is more generic?

**Comment by IDragonfire** [comment]
@bwvoss my error message is valid

````
Error objects provide additional information about problems encountered while performing an operation. Error objects MUST be returned as an array keyed by errors in the top level of a JSON API document.

An error object MAY have the following members:
.... 
```

`source` and `pointer` are optional from my understanding...

**Comment by bwvoss** [comment]
@IDragonfire yep, you are right.  For clarity, this is the line that is causing your problems: https://github.com/twg/devour/blob/master/src/middleware/json-api/res-errors.js#L15

Try replacing the middleware -- its pretty much as straightforward as the example in the README.

**Comment by samtgarson** [comment]
Are there any plans to handle this situation in the long run? Most of the errors I've had when using this client have been non-validation-related, so would seem to be sensible to at least not blow up if this key isn't present? When I have some time I'll submit a PR?

**Comment by SirLamer** [comment]
This issue is causing my trouble as well. I will be replacing the error handler as a patch solution.

**Comment by grk** [comment]
@SirLamer would you mind sharing the middleware that fixes that problem?

**Comment by SirLamer** [comment]
I haven't quite gotten there yet. ;-)

In fact, I am likely to switch to a different, simpler package for reasons external to this error handling issue. I may also may end up integrating that package as a middleware as well, in which case yes I'll do the same for error handling, but at the moment I don't have something to share.

In effect, you need to alter the attempt to read the pointer field to expect that it may not be present. Typically the pointer field is included only when form validation fails, as oppose to a runtime error or something else like that.

**Comment by mateomurphy** [comment]
I've been using 
```
errorMiddleware = {
  name: 'pass-errors-through',
  error: function (payload) {
    return payload.data.errors
  }
}
```

Which is very barebones but works for me

**Comment by toadle** [comment]
Same here. My Rails/JSON API-error middleware. Handles per-field errors: 

```
let errorMiddleware = {
  name: 'error-middleware',
  error: (payload) => {
    if(payload.status == 401) {
      return {
        request: {
          authorized: false
        }
      };
    } else {
      var data = payload.data;
      if (!data.errors) {
        console.log('Unidentified error');
        console.log(payload);
        return;
      } else {
        let errors = {};
        data.errors.forEach((error) => {
          errors[error.meta.attribute] = {};
          errors[error.meta.attribute][error.code] = false;
        });
        return errors;
      }
    }
  }
};
jsonApi.replaceMiddleware('errors', errorMiddleware);
```

**Comment by Emerson** [comment]
I'm not 100% sure, but I think the newest 2.0 release handles this in a more graceful manner.

**Comment by jtrees** [comment]
I can confirm this issue is still present with devour 2.0.7. Request re-opening.

**Comment by SirLamer** [comment]
I ended up sticking with Devour. I think it's resolved? I guess I'm not sure however I get the proper error handling as expected.

Someone above asked for my error handler, here it is. Note that I am wildly changing the error response because I want to collect validation errors for display to the user in my UI solution. So just heads-up, this totally changes the data pattern in the response.

```js
const errorMiddleware = {
    name: 'error-middleware',
    error: (payload) => {
        const errors = get(payload, 'response.data.errors', []);
        if (errors.length === 0) {
            return errors;
        }

        const grouped = groupBy(errors, 'status');
        if (grouped['422']) {
            const messages = {};
            grouped['422'].forEach((error) => {
                const buffer = error;
                const pointer = error.source.pointer.split('/');
                buffer.message = error.detail;
                delete buffer.detail;
                buffer.name = camelCase(pointer[pointer.length - 1]);
                buffer.type = pointer[pointer.length - 2];
                if (!messages[buffer.name]) {
                    messages[buffer.name] = [];
                }
                messages[buffer.name].push(buffer);
            });
            grouped['422'] = messages;
        }

        return grouped;
    }
};
```
