### ISSUE TITLE
POST to hasMany relationship incorrectly includes empty 'attributes' objects

### ISSUE THREAD

**Issue by SirLamer** [twg/devour#96]
Per API spec here: http://jsonapi.org/format/#crud-updating-to-many-relationships

hasMany relationships can be bound via a POST action to the relationship URL:

implementation example (this is a sync action which adds all available 'devices' to a 'project')
```js
            addDevicesToProject() {
                this.startEvent();

                return new Promise((resolve, reject) => {
                    //const create = [];

                    const create = this.availableDevices.map((device) => {
                        return {type: 'devices', id: device.id}
                    });
                    JsonApi.one('project', this.project.id).all('device').post(create)
                        .then((responses) => {
                            this.successEvent(responses);
                            console.log('addDevices', responses);
                            resolve(responses);
                        })
                        .catch((error) => {
                            this.errorEvent(error);
                            reject(error);
                        });
                });
            }
```
In the above, the "create" const is prepared with an array of relationship objects. 

The prepared payload is:
```
{"data":[{"type":"devices","attributes":{},"id":"27"},{"type":"devices","attributes":{},"id":"28"}],"meta":{}}
```

The 'attributes' fields are unnecessary and cause problems.

I am testing with a version 2.0.3.

**Comment by SirLamer** [comment]
I came here to close this but I see a fix references this...

My feedback is in error largely because relationship binds are not meant to be sent via POST to this URL. It is missing the "relationships" part of the URL.

For now I came up with a hacky middleware to get around this limitation in Devour.

**Comment by masimons** [comment]
@SirLamer I created a PR - I've tested this fix in my project.

Just have to get the build passing.

https://github.com/twg/devour/pull/98

**Comment by masimons** [comment]
To get around the "relationships" part missing, I've called `.all('relationships)` ¯\_(ツ)_/¯

**Comment by SirLamer** [comment]
Yes your solution for attributes nonetheless seems appropriate in general, even though my initial issue comment is invalid.
